#cloud-config
users:
  - name: quantumplation
    groups: sudo
    shell: /bin/zsh
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBNuZeecpmC4PONhgGpkggrtmEk6+hhd8H9koS8Y0fnNYE7JLsuH4SLKsSMmdyzGMa8dZCGIdbvxBKXTmO+nl70c4aHfqmyQoo0bXxi/ZpkE0g9M91aySvX/xdjBEwjeFgQ== ECDSA Kovalevskaya
packages:
  - zsh
runcmd:
  - echo "Installing ohmyzsh..."
  - runuser -l quantumplation -c 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"'
  - echo "Setting up dotfiles..."
  - runuser -l quantumplation -c 'git clone --recursive https://github.com/Quantumplation/Dotfiles.git /home/quantumplation/Dotfiles'
  - runuser -l quantumplation -c '/home/quantumplation/Dotfiles/install.sh'